# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pathToProject: 'web'
  pathToSolution: ''

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'team2-skep'
    organization: '1905-may06-dotnet'
    scannerMode: 'MSBuild'
    projectKey: 'skep'
    projectName: 'team2-skep-project2'
# - script: hello world!
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(pathToProject)
- task: SonarCloudAnalyze@1
- script: dotnet publish  --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathToProject)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathToProject)/*.csproj'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(f76f9b2a-8aaa-49c1-b980-cd3c8191f17a)'
    appType: 'webApp'
    WebAppName: 'team3-skep'
    RuntimeStack: 'DOTNETCORE|2.2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/$(pathtoproject)/**/*.zip'