# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - front
      - GSBGM

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker

steps:
- script: |
    docker login -u $(dockerId) -p "$(dockerPassword)"
- task: Docker@2
  inputs:
    arguments: -t kevincloinger/skep:CSharp
    command: 'build'
    Dockerfile: '**/Dockerfile'
- script: |
    docker push kevincloinger/skep