# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script:  dotnet build web/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'team3-skep-project'
    appType: 'webAppLinux'
    appName: 'team3-skep'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|2.2'
    startUpCommand: 'dotnet run web/'