# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - front

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pathToProject: 'web'
  pathToSolution: ''

steps:
- task: Docker@2
  inputs:
    repository: 'skepdocker.azurecr.io'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'