# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script:  dotnet publish web/ --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(f76f9b2a-8aaa-49c1-b980-cd3c8191f17a)'
    appType: 'webApp'
    WebAppName: 'team3-skep'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'