# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pathToProject: 'web'
  pathToSolution: ''

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'

- task: Docker@2
  inputs:
    repository: '/subscriptions/f76f9b2a-8aaa-49c1-b980-cd3c8191f17a/resourceGroups/team3-skep/providers/Microsoft.ContainerRegistry/registries/skepBuilds'
    command: 'push'