# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - GSBGM

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    repository: 'skepdocker.azurecr.io'
    command: 'build'
    Dockerfile: 'GSBGM/Dockerfile'
    tags: "NGDeploy"
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(f76f9b2a-8aaa-49c1-b980-cd3c8191f17a)'
    appType: 'webAppContainer'
    WebAppName: 'GSBGM'
    DockerNamespace: 'skepdocker.azurecr.io'
    DockerImageTag: 'NGDeploy'