# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - GSBGM

pool:
  vmImage: 'ubuntu-latest'
variables:
  dockerId: kevin.cloinger@gmail.com
  imageName: NGSkep

steps:
- bash: echo $(bob)
- script: |
    docker login -u $(dockerId) -p "$(dockerPassword)"
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'GSBGM/Dockerfile'
    tags: "NGDeploy"
